FB.blocks = {};

FB.blocks.BLOCK_DEFS = {
  nav: {
    label: "Navigation",
    sublabel: "Logo + links + CTA",
    icon: "≡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Work", "Services", "About", "Contact"],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      menuStyle: "simple",
    },
  },
  hero: {
    label: "Hero",
    sublabel: "Full-screen opener",
    icon: "H",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Nottingham · Est. 2026",
      headline: "We build things that <em>matter.</em>",
      subtext:
        "Bold brand and web design for businesses that refuse to be ordinary.",
      ctaText: "See our work →",
      bg: "#111111",
      accentColor: "#CDFE00",
      showBlob: true,
      blobStyle: "blob",
      // NEW: Image support
      heroImage: "",
      imageOpacity: 0.3,
      overlayColor: "rgba(0,0,0,0.4)",
    },
  },
  marquee: {
    label: "Marquee Strip",
    sublabel: "Scrolling keyword band",
    icon: "»»",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Award Winning",
        "Creative",
        "Results Driven",
        "Human Centred",
        "Boldly Different",
      ],
      bg: "#CDFE00",
      textColor: "#111111",
      speed: 16,
    },
  },
  work: {
    label: "Work Grid",
    sublabel: "5-card project showcase",
    icon: "⊞",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our work.",
      headline: "Selected projects.",
      cards: [
        {
          tag: "Fintech · Platform",
          title: "Project One",
          desc: "A bold digital platform for modern finance.",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
          imageUrl: "",
          textColor: "#f7f6f2",
        },
        {
          tag: "SaaS · Brand",
          title: "Project Two",
          desc: "Brand identity for a fast-growing SaaS.",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
          imageUrl: "",
          textColor: "#f7f6f2",
        },
        {
          tag: "E-commerce · UI",
          title: "Project Three",
          desc: "Commerce experience that converts.",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
          imageUrl: "",
          textColor: "#f7f6f2",
        },
        {
          tag: "Mobile · App",
          title: "Project Four",
          desc: "Award-winning mobile app design.",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
          imageUrl: "",
          textColor: "#f7f6f2",
        },
        {
          tag: "Web · Strategy",
          title: "Project Five",
          desc: "Full-stack web strategy and execution.",
          bg: "linear-gradient(135deg,#1a1a1a,#3a3a3a)",
          imageUrl: "",
          textColor: "#f7f6f2",
        },
      ],
      bg: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  services: {
    label: "Services List",
    sublabel: "Large text row layout",
    icon: "≫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Brand Strategy",
        "Web Design",
        "Development",
        "SEO & Growth",
        "Content Creation",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  stats: {
    label: "Stats Counter",
    sublabel: "Animated number counters",
    icon: "#",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      stats: [
        { num: "150+", label: "Projects Delivered" },
        { num: "98%", label: "Client Retention" },
        { num: "12", label: "Industry Awards" },
        { num: "5M+", label: "Revenue Generated" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  testimonial: {
    label: "Testimonial",
    sublabel: "Client quote + avatar",
    icon: '"',
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      quote:
        "They transformed our brand completely. The results speak for themselves — 3x more leads in just 60 days.",
      name: "Sarah Mitchell",
      role: "CEO, TechForward",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  process: {
    label: "Process Steps",
    sublabel: "Numbered workflow stages",
    icon: "①",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      steps: [
        {
          num: "01",
          title: "Discovery",
          desc: "We learn about your brand, goals, and audience.",
        },
        {
          num: "02",
          title: "Design",
          desc: "Bold concepts that stand out from the noise.",
        },
        {
          num: "03",
          title: "Build",
          desc: "Pixel-perfect development with clean code.",
        },
        {
          num: "04",
          title: "Launch",
          desc: "Go live with confidence and ongoing support.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cta: {
    label: "Call to Action",
    sublabel: "Bold conversion section",
    icon: "→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Ready to stand out?",
      subtext: "Let's build something extraordinary together.",
      btnText: "Start a project",
      bg: "#CDFE00",
      textColor: "#111111",
      accentColor: "#111111",
    },
  },
  footer: {
    label: "Footer",
    sublabel: "Links + social + copyright",
    icon: "▁",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      brandName: "YourBrand.",
      tagline: "Bold design for bold businesses.",
      columns: [
        {
          heading: "Services",
          links: ["Web Design", "Branding", "Development", "SEO"],
        },
        { heading: "Company", links: ["About", "Careers", "Blog", "Contact"] },
        { heading: "Legal", links: ["Privacy", "Terms", "Cookies"] },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  features: {
    label: "Features Grid",
    sublabel: "Icon + title + description cards",
    icon: "⚡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Why choose us",
      headline: "Built different.",
      items: [
        {
          icon: "⚡",
          title: "Lightning Fast",
          desc: "Optimized for speed and performance.",
          // NEW: Optional image per feature
          image: "",
          useImage: false,
        },
        {
          icon: "🎨",
          title: "Bold Design",
          desc: "Stand out from the competition.",
          image: "",
          useImage: false,
        },
        {
          icon: "📱",
          title: "Responsive",
          desc: "Perfect on every device.",
          image: "",
          useImage: false,
        },
        {
          icon: "🔒",
          title: "Secure",
          desc: "Enterprise-grade security.",
          image: "",
          useImage: false,
        },
        {
          icon: "📈",
          title: "SEO Ready",
          desc: "Built to rank on search engines.",
          image: "",
          useImage: false,
        },
        {
          icon: "🤝",
          title: "Support",
          desc: "Ongoing help when you need it.",
          image: "",
          useImage: false,
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      // NEW: Feature card image sizing
      featureImageSize: 80,
      featureImageRadius: 8,
    },
  },
  pricing: {
    label: "Pricing Table",
    sublabel: "3-tier pricing cards",
    icon: "$",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Pricing",
      headline: "Simple, transparent pricing.",
      tiers: [
        {
          name: "Starter",
          price: "£999",
          period: "/project",
          features: [
            "5 pages",
            "Mobile responsive",
            "Basic SEO",
            "1 revision round",
          ],
          cta: "Get started",
          highlighted: false,
          // NEW: Optional image per plan
          image: "",
        },
        {
          name: "Professional",
          price: "£2,499",
          period: "/project",
          features: [
            "10 pages",
            "Mobile responsive",
            "Advanced SEO",
            "3 revision rounds",
            "Analytics setup",
            "CMS integration",
          ],
          cta: "Most popular",
          highlighted: true,
          image: "",
        },
        {
          name: "Enterprise",
          price: "£4,999",
          period: "/project",
          features: [
            "Unlimited pages",
            "Mobile responsive",
            "Full SEO suite",
            "Unlimited revisions",
            "Analytics setup",
            "Custom integrations",
            "Priority support",
          ],
          cta: "Contact us",
          highlighted: false,
          image: "",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      // NEW: Pricing card image sizing
      pricingImageSize: 120,
      pricingImageRadius: 8,
    },
  },
  team: {
    label: "Team Grid",
    sublabel: "Member photos + roles",
    icon: "👥",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our team",
      headline: "Meet the crew.",
      members: [
        {
          name: "Alex Chen",
          role: "Creative Director",
          imageUrl:
            "https://images.unsplash.com/photo-1507003211169-465903714315?w=400",
        },
        {
          name: "Sam Rivera",
          role: "Lead Developer",
          imageUrl:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
        },
        {
          name: "Jordan Lee",
          role: "UX Designer",
          imageUrl:
            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
        },
        {
          name: "Morgan Park",
          role: "Strategist",
          imageUrl:
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  videoHero: {
    label: "Video Hero",
    sublabel: "Background video opener",
    icon: "▶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We create digital experiences.",
      subtext: "Bold, immersive, and unforgettable.",
      ctaText: "Watch our showreel",
      ctaPrimary: "Watch our showreel",
      ctaSecondary: "Learn more",
      videoUrl: "",
      overlayColor: "#000000",
      overlayOpacity: 0.4,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitHero: {
    label: "Split Hero",
    sublabel: "Text left, image right",
    icon: "◫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Welcome",
      headline: "Design that converts.",
      subtext:
        "We blend creativity with strategy to build websites that don't just look good — they perform.",
      ctaText: "See our work",
      embedType: "image",
      embedUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      imageAlt: "Hero image",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  orbsHero: {
    label: "Orbs Hero",
    sublabel: "Animated gradient orbs",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We design for the bold.",
      subtext: "Not the safe. Not the ordinary. The bold.",
      ctaText: "Explore our work",
      bg: "#0a0a0a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      orbs: [
        { size: 45, x: -5, y: -15, color: "#4b2de8", opacity: 0.65 },
        { size: 35, x: 65, y: 55, color: "#d31468", opacity: 0.55 },
        { size: 28, x: 40, y: 5, color: "#00c9ff", opacity: 0.45 },
      ],
    },
  },
  megaNav: {
    label: "Mega Navigation",
    sublabel: "Dropdown with columns",
    icon: "☰",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: [
        {
          label: "Services",
          columns: [
            {
              heading: "Design",
              items: ["Web Design", "Brand Identity", "UI/UX"],
            },
            { heading: "Build", items: ["Development", "CMS", "E-commerce"] },
          ],
        },
        { label: "Work", url: "#" },
        { label: "About", url: "#" },
        { label: "Contact", url: "#" },
      ],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  slideNav: {
    label: "Slide Navigation",
    sublabel: "Animated slide-in nav",
    icon: "⊳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Work", "Services", "About", "Blog", "Contact"],
      ctaText: "Let's talk",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  resultsGrid: {
    label: "Results Grid",
    sublabel: "Data-driven showcase",
    icon: "▦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Results",
      headline: "Numbers that speak.",
      subtitle: "Real outcomes for real businesses.",
      cards: [
        {
          type: "E-commerce",
          clientName: "Urban Thread",
          location: "London, UK",
          description: "Full brand refresh and Shopify build.",
          metrics: [
            { label: "Conversion Rate", before: "1.2%", after: "4.1%", note: "240% uplift" },
            { label: "Revenue", before: "£42k/mo", after: "£118k/mo", note: "3× growth" },
          ],
          testimonial: { name: "Sarah K.", brand: "Urban Thread", quote: "Best investment we ever made." },
        },
        {
          type: "SaaS",
          clientName: "FlowMetrics",
          location: "Edinburgh, UK",
          description: "Product redesign and go-to-market site.",
          metrics: [
            { label: "Trial Signups", before: "180/mo", after: "640/mo", note: "+256%" },
            { label: "Churn Rate", before: "8.4%", after: "2.1%", note: "−75%" },
          ],
          testimonial: { name: "James L.", brand: "FlowMetrics", quote: "We closed our Series A 3 months later." },
        },
        {
          type: "Professional Services",
          clientName: "Apex Legal",
          location: "Manchester, UK",
          description: "Authority brand and content strategy.",
          metrics: [
            { label: "Inbound Leads", before: "12/mo", after: "67/mo", note: "+458%" },
            { label: "Avg. Deal Size", before: "£3.2k", after: "£8.9k", note: "+178%" },
          ],
          testimonial: { name: "Priya M.", brand: "Apex Legal", quote: "We look like a top-10 firm now." },
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  glassCards: {
    label: "Glass Cards",
    sublabel: "Frosted glass effect cards",
    icon: "◇",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "What we offer.",
      cards: [
        { title: "Brand Strategy", desc: "Define your voice and stand out." },
        { title: "Web Design", desc: "Beautiful, functional websites." },
        {
          title: "Growth Marketing",
          desc: "Data-driven campaigns that convert.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  portfolioGrid: {
    label: "Portfolio Grid",
    sublabel: "Masonry-style project gallery",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Portfolio",
      headline: "Selected work.",
      items: [
        {
          title: "Project Alpha",
          category: "Web Design",
          desc: "A bold digital experience.",
          imageUrl:
            "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600",
        },
        {
          title: "Project Beta",
          category: "Branding",
          desc: "Identity that stands out.",
          imageUrl:
            "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600",
        },
        {
          title: "Project Gamma",
          category: "E-commerce",
          desc: "Commerce that converts.",
          imageUrl:
            "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  clientCarousel: {
    label: "Client Carousel",
    sublabel: "Scrolling logo strip",
    icon: "◎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Trusted by leading brands",
      clients: [
        "Acme Corp",
        "TechCo",
        "DesignLab",
        "StartupXYZ",
        "BrandHQ",
        "MediaPlus",
        "NovaCo",
        "Apex Studio",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      style: "pill",
      mode: "marquee",
      twoRows: false,
      speed: 30,
      separator: "✦",
      fontSize: 14,
      gap: 24,
      showLabel: true,
      paddingV: 48,
    },
  },
  trustPill: {
    label: "Trust Pill",
    sublabel: "Rating + verified badge",
    icon: "✓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      ratingText: "Google Reviews",
      verifiedDate: "Verified Business",
      ratingCount: 5,
      starColor: "#FFD700",
      bg: "#111111",
      textColor: "#f7f6f2",
    },
  },
  metricBox: {
    label: "Metric Box",
    sublabel: "Single stat highlight",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      value: "97%",
      label: "Client satisfaction rate",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  wordSwap: {
    label: "Word Swap",
    sublabel: "Animated text rotation",
    icon: "⟳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      prefix: "We build",
      words: [
        { text: "brands", gradient: "lime" },
        { text: "websites", gradient: "teal" },
        { text: "experiences", gradient: "rose" },
        { text: "futures", gradient: "coffee" },
      ],
      suffix: "that matter.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  chatWidget: {
    label: "Chat Widget",
    sublabel: "Floating chat bubble",
    icon: "💬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      greeting: "Hi! How can we help?",
      btnText: "Chat with us",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cookieConsent: {
    label: "Cookie Consent",
    sublabel: "GDPR cookie banner",
    icon: "🍪",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      title: "🍪 Cookies",
      message: "We use cookies to enhance your experience.",
      acceptText: "Accept All",
      declineText: "Decline",
      customizeText: "Customize",
      bg: "#1a1a1a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      categories: [
        {
          id: "functional",
          name: "Functional",
          description: "Essential for the site to function properly.",
          required: true,
        },
        {
          id: "analytics",
          name: "Analytics",
          description: "Help us understand how visitors use the site.",
          required: false,
        },
        {
          id: "marketing",
          name: "Marketing",
          description: "Used to deliver relevant ads and content.",
          required: false,
        },
      ],
    },
  },
  liteVideo: {
    label: "Lite Video",
    sublabel: "Lazy-loaded video embed",
    icon: "🎬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      thumbnailUrl:
        "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      caption: "Our showreel 2026",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  faq: {
    label: "FAQ Accordion",
    sublabel: "Expandable Q&A section",
    icon: "?",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "FAQ",
      headline: "Common questions.",
      items: [
        {
          q: "How long does a project take?",
          a: "Typically 4-8 weeks depending on scope.",
        },
        {
          q: "Do you offer ongoing support?",
          a: "Yes, all plans include post-launch support.",
        },
        {
          q: "What's your pricing?",
          a: "Projects start at £999. Contact us for a quote.",
        },
        {
          q: "Can you work with existing brands?",
          a: "Absolutely — we adapt to your brand guidelines.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitText: {
    label: "Split Text",
    sublabel: "Character-by-character animation",
    icon: "Aa",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Animated text.",
      subtext: "Each character animates in on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  maskReveal: {
    label: "Mask Reveal",
    sublabel: "Clip-path reveal animation",
    icon: "▨",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Revealed on scroll.",
      subtext: "Bold design that emerges as you discover it.",
      ctaText: "",
      imageUrl: "",
      animType: "slideUp",
      fontSize: 4,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  fullscreenMenu: {
    label: "Fullscreen Menu",
    sublabel: "Full-screen navigation overlay",
    icon: "⛶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Home", "Work", "Services", "About", "Contact"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  circularList: {
    label: "Circular List",
    sublabel: "Rotating circular items",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: ["Design", "Develop", "Deploy", "Grow", "Optimise", "Scale"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      label: "How we work",
      centerText: "6",
      centerSubtext: "steps",
      mode: "ring",
      itemStyle: "pill",
      ringSize: 320,
      showConnectors: true,
      autoRotate: false,
      rotateSpeed: 25,
      glowItems: false,
      showNumbers: true,
      fontSize: 12,
      paddingV: 80,
      ringBorder: true,
      multiColor: false,
    },
  },
  glitchText: {
    label: "Glitch Text",
    sublabel: "RGB glitch effect",
    icon: "G",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "GLITCH.",
      subtext: "Reality is breaking apart.",
      fontSize: 6,
      fontWeight: 900,
      glitchIntensity: 3,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  svgDraw: {
    label: "SVG Draw",
    sublabel: "Animated stroke drawing",
    icon: "✎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Drawn on scroll.",
      subtext: "Scroll down to animate the stroke.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      animDuration: 3,
    },
  },
  dayNightSwitcher: {
    label: "Day/Night Switch",
    sublabel: "Theme toggle section",
    icon: "☀",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      dayText: "Day mode",
      nightText: "Night mode",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  particleButton: {
    label: "Particle Button",
    sublabel: "Hover particle effect CTA",
    icon: "✦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Hover me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  noiseSection: {
    label: "Noise Section",
    sublabel: "Film grain texture overlay",
    icon: "▒",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Textured.",
      subtext: "Film grain adds depth and character.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  scrollIndicator: {
    label: "Scroll Indicator",
    sublabel: "Animated scroll prompt",
    icon: "↓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      text: "Scroll to explore",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  timeline: {
    label: "Timeline",
    sublabel: "Vertical milestone layout",
    icon: "│",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Our journey.",
      events: [
        {
          year: "2020",
          title: "Founded",
          desc: "Started in a Nottingham garage.",
        },
        {
          year: "2022",
          title: "First office",
          desc: "Moved into our creative studio.",
        },
        {
          year: "2024",
          title: "50 clients",
          desc: "Hit our biggest milestone yet.",
        },
        {
          year: "2026",
          title: "Going global",
          desc: "Expanding to international markets.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  iridescentBtn: {
    label: "Iridescent Button",
    sublabel: "Holographic gradient CTA",
    icon: "◈",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Click me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  counterSection: {
    label: "Counter Section",
    sublabel: "Animated counting numbers",
    icon: "0→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      counters: [
        { target: 500, suffix: "+", label: "Happy clients" },
        { target: 1200, suffix: "+", label: "Projects done" },
        { target: 15, suffix: "", label: "Team members" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  socialLinks: {
    label: "Social Links",
    sublabel: "Multi-platform social hub",
    icon: "◎",
    iconBg: "#1a0a1e",
    iconColor: "#ec4899",
    defaultProps: {
      label: "Follow the Journey",
      headline: "Stay connected.",
      style: "cards",
      showHandles: true,
      showFollowers: true,
      showLabel: true,
      usePlatformColors: true,
      gap: 16,
      paddingV: 80,
      columns: 3,
      bg: "#0a0a0f",
      textColor: "#f7f6f2",
      accentColor: "#ec4899",
      networks: [
        {
          platform: "instagram",
          handle: "@yourbrand",
          followers: "12.4K",
          url: "#",
        },
        {
          platform: "twitter",
          handle: "@yourbrand",
          followers: "8.2K",
          url: "#",
        },
        {
          platform: "tiktok",
          handle: "@yourbrand",
          followers: "45.1K",
          url: "#",
        },
        {
          platform: "youtube",
          handle: "Your Brand",
          followers: "3.1K",
          url: "#",
        },
        {
          platform: "linkedin",
          handle: "Your Brand",
          followers: "2.8K",
          url: "#",
        },
        {
          platform: "github",
          handle: "yourbrand",
          followers: "1.2K",
          url: "#",
        },
      ],
    },
  },
  whatsappWidget: {
    label: "WhatsApp Connect",
    sublabel: "Direct WhatsApp CTA",
    icon: "✆",
    iconBg: "#0a1f0d",
    iconColor: "#25D366",
    defaultProps: {
      phone: "+447700000000",
      message: "Hi! I'd love to find out more about your services.",
      style: "card",
      label: "Chat with us",
      subtext: "Typically replies within minutes",
      buttonText: "Start a conversation",
      showStatus: true,
      statusText: "Online now",
      avatarBg: "#128C7E",
      bg: "#0a0a0a",
      textColor: "#f7f6f2",
      accentColor: "#25D366",
      paddingV: 64,
    },
  },
  cornerSection: {
    label: "Corner Section",
    sublabel: "Decorative corner borders",
    icon: "┌",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Framed.",
      subtext: "Corner accents add editorial polish.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  horizontalScroll: {
    label: "Horizontal Scroll",
    sublabel: "Side-scrolling card gallery",
    icon: "⇉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Featured Work",
      headline: "Projects that move.",
      subtext: "Drag or use arrows to explore",
      mode: "cards",
      cardStyle: "gradient",
      cardWidth: 320,
      showNumbers: true,
      showProgress: true,
      showArrows: true,
      showSubtitle: true,
      showTags: true,
      gap: 24,
      paddingV: 80,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      cards: [
        {
          category: "Fintech",
          title: "Project One",
          subtitle: "Brand identity & product design",
          tag: "2024",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
        },
        {
          category: "SaaS",
          title: "Project Two",
          subtitle: "Full-stack web application",
          tag: "2024",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
        },
        {
          category: "E-commerce",
          title: "Project Three",
          subtitle: "Conversion-focused redesign",
          tag: "2023",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
        },
        {
          category: "Mobile",
          title: "Project Four",
          subtitle: "iOS & Android experience",
          tag: "2023",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
        },
        {
          category: "Branding",
          title: "Project Five",
          subtitle: "Visual identity system",
          tag: "2022",
          bg: "linear-gradient(135deg,#2a1a3a,#5e1a7e)",
        },
      ],
    },
  },
};

FB.blocks.CUSTOM_BLOCK_DEFS = {
  textBlock: {
    label: "Custom Text",
    sublabel: "Heading + paragraph",
    icon: "T",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Your Headline Here",
      body: "Your body text goes here. Click to edit inline, or use the style panel on the right to change colours and spacing.",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#CDFE00",
      paddingV: 64,
      paddingH: 48,
    },
  },
  colorBlock: {
    label: "Colour Block",
    sublabel: "Full-width colour section",
    icon: "■",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Bold Statement.",
      body: "A full-colour section for emphasis.",
      bg: "#CDFE00",
      textColor: "#111111",
      paddingV: 80,
      paddingH: 48,
    },
  },
  imageTextTop: {
    label: "Image + Text (Top)",
    sublabel: "Image above text",
    icon: "◰",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that describes the image above. Click to edit any content.",
      imageUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      imageAlt: "Section image",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 0,
      imagePosition: "top",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextBottom: {
    label: "Image + Text (Bottom)",
    sublabel: "Text above image",
    icon: "◳",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that introduces the image below.",
      imageUrl:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800",
      imageAlt: "Team collaboration",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 12,
      imagePosition: "bottom",
      textAlign: "center",
      bg: "#f8fafc",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextLeft: {
    label: "Image + Text (Left)",
    sublabel: "Image left, text right",
    icon: "◧",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Great for feature descriptions or about sections.",
      imageUrl:
        "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600",
      imageAlt: "Feature showcase",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "left",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
  imageTextRight: {
    label: "Image + Text (Right)",
    sublabel: "Text left, image right",
    icon: "◨",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Perfect for testimonials or case studies.",
      imageUrl:
        "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600",
      imageAlt: "Case study",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "right",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
};

FB.blocks.ECOMMERCE_DEFS = {
  ecomProductCard: {
    label: "Product Card",
    sublabel: "Image + price + cart button",
    icon: "🛒",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
      title: "Premium Watch",
      price: "£129.00",
      salePrice: "",
      rating: 4,
      reviewCount: 24,
      btnText: "Add to Cart",
      badge: "",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductGrid: {
    label: "Product Grid",
    sublabel: "Multi-column product layout",
    icon: "⊞",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      columns: 3,
      gap: 24,
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Premium Watch",
          price: "£129.00",
          salePrice: "",
          rating: 4,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Wireless Headphones",
          price: "£89.00",
          salePrice: "£69.00",
          rating: 5,
          badge: "Sale",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Sunglasses",
          price: "£45.00",
          salePrice: "",
          rating: 3,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Leather Boots",
          price: "£199.00",
          salePrice: "",
          rating: 5,
          badge: "New",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
          title: "Perfume",
          price: "£75.00",
          salePrice: "",
          rating: 4,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
          title: "Backpack",
          price: "£110.00",
          salePrice: "£85.00",
          rating: 4,
          badge: "Sale",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomFeaturedProduct: {
    label: "Featured Product",
    sublabel: "Split layout with details",
    icon: "★",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
      title: "Premium Chronograph Watch",
      description:
        "Handcrafted stainless steel timepiece with sapphire crystal glass. Water resistant to 100m. Swiss automatic movement with 42-hour power reserve.",
      price: "£349.00",
      salePrice: "£279.00",
      variants: "Black / Silver / Rose Gold",
      btnText: "Add to Cart",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductCarousel: {
    label: "Product Carousel",
    sublabel: "Scrollable product strip",
    icon: "⟳",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      cardsVisible: 4,
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Watch",
          price: "£129.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Headphones",
          price: "£89.00",
          salePrice: "£69.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Sunglasses",
          price: "£45.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Boots",
          price: "£199.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
          title: "Perfume",
          price: "£75.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
          title: "Backpack",
          price: "£110.00",
          salePrice: "£85.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400",
          title: "Smart Watch",
          price: "£249.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400",
          title: "Sneakers",
          price: "£135.00",
          salePrice: "",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomQuickView: {
    label: "Quick View",
    sublabel: "Modal product preview",
    icon: "👁",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      triggerText: "Quick View Product",
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
      title: "Premium Watch",
      price: "£129.00",
      salePrice: "",
      description: "Click to open a modal quick-view of this product.",
      btnText: "Add to Cart",
      modalBg: "#1a1a1a",
      overlayOpacity: 0.8,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomCartDrawer: {
    label: "Cart Drawer",
    sublabel: "Slide-in cart panel",
    icon: "🛍",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      emptyText: "Your cart is empty",
      checkoutBtnText: "Checkout",
      bg: "#1a1a1a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCartSummary: {
    label: "Cart Summary",
    sublabel: "Subtotal + tax + total",
    icon: "Σ",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      shippingText: "Shipping",
      taxRate: 20,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCheckoutForm: {
    label: "Checkout Form",
    sublabel: "Billing + order summary",
    icon: "📋",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      heading: "Checkout",
      btnText: "Place Order",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomSaleBanner: {
    label: "Sale Banner",
    sublabel: "Discount announcement strip",
    icon: "🔥",
    iconBg: "#ef4444",
    iconColor: "#fff",
    defaultProps: {
      headline: "SUMMER SALE",
      subtext: "Up to 50% off selected items",
      btnText: "Shop Now",
      btnUrl: "#",
      bg: "#ef4444",
      textColor: "#ffffff",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomCountdown: {
    label: "Countdown Timer",
    sublabel: "Days / hours / mins / secs",
    icon: "⏱",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Sale Ends In",
      targetDate: "2026-06-01T00:00:00",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCouponInput: {
    label: "Coupon Input",
    sublabel: "Promo code field",
    icon: "🏷",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Have a promo code?",
      placeholder: "Enter code here",
      btnText: "Apply",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomShippingProgress: {
    label: "Shipping Progress",
    sublabel: "Free shipping threshold bar",
    icon: "📦",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      threshold: 50,
      currentAmount: 32,
      headline: "Free shipping on orders over £50",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomReviews: {
    label: "Product Reviews",
    sublabel: "Star ratings + review cards",
    icon: "⭐",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      rating: 4.7,
      reviewCount: 128,
      reviews: [
        {
          name: "Sarah M.",
          rating: 5,
          date: "2 days ago",
          text: "Absolutely love this product! Quality is outstanding and delivery was super fast.",
        },
        {
          name: "James T.",
          rating: 4,
          date: "1 week ago",
          text: "Great value for money. Would recommend to anyone looking for a reliable option.",
        },
        {
          name: "Emma L.",
          rating: 5,
          date: "2 weeks ago",
          text: "Exceeded my expectations. The attention to detail is remarkable.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomFilters: {
    label: "Filters & Sort",
    sublabel: "Category, price, sort controls",
    icon: "⚙",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      categories: ["All", "Clothing", "Accessories", "Footwear", "Electronics"],
      sortOptions: [
        "Featured",
        "Price: Low to High",
        "Price: High to Low",
        "Newest",
        "Best Rating",
      ],
      showPriceRange: true,
      showGridToggle: true,
      resultsText: "24 products found",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomTrustBadges: {
    label: "Trust Badges",
    sublabel: "Secure checkout, returns, warranty icons",
    icon: "🛡",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      badges: [
        {
          icon: "🔒",
          title: "Secure Checkout",
          desc: "256-bit SSL encryption",
        },
        { icon: "🔄", title: "Free Returns", desc: "30-day return policy" },
        { icon: "🚚", title: "Free Shipping", desc: "Orders over £50" },
        { icon: "⭐", title: "Top Rated", desc: "4.9/5 from 2,000+ reviews" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomNewsletter: {
    label: "Newsletter Signup",
    sublabel: "Email capture with discount offer",
    icon: "✉",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Get 10% Off Your First Order",
      subtext:
        "Join our mailing list for exclusive deals, new arrivals, and style inspiration.",
      placeholder: "Enter your email",
      btnText: "Subscribe",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomRelatedProducts: {
    label: "Related Products",
    sublabel: "You might also like section",
    icon: "🔗",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      heading: "You Might Also Like",
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Classic Watch",
          price: "£129.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Wireless Earbuds",
          price: "£89.00",
          salePrice: "£69.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Aviator Sunglasses",
          price: "£45.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Leather Wallet",
          price: "£59.00",
          salePrice: "",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductTabs: {
    label: "Product Tabs",
    sublabel: "Description / Specs / Reviews tabs",
    icon: "📑",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      tabs: [
        {
          label: "Description",
          content:
            "<p>Our premium collection features handcrafted materials with attention to every detail. Each piece is designed to combine style with functionality, ensuring you look your best while enjoying lasting quality.</p><p>Features include premium materials, expert craftsmanship, and a satisfaction guarantee.</p>",
        },
        {
          label: "Specifications",
          content:
            "<table><tr><td>Material</td><td>Premium Stainless Steel</td></tr><tr><td>Weight</td><td>120g</td></tr><tr><td>Dimensions</td><td>42mm × 12mm</td></tr><tr><td>Water Resistance</td><td>100m / 10 ATM</td></tr><tr><td>Warranty</td><td>2 Years</td></tr></table>",
        },
        {
          label: "Shipping",
          content:
            "<p><strong>Standard Shipping:</strong> 3-5 business days — £4.99</p><p><strong>Express Shipping:</strong> 1-2 business days — £9.99</p><p><strong>Free Shipping:</strong> On orders over £50</p><p>International shipping available to 40+ countries.</p>",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  kineticText: {
    label: "Kinetic Text",
    sublabel: "Scrambling text reveal with kinetic energy",
    icon: "✦",
    iconBg: "#1a3a2a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Kinetic Energy",
      subtext: "Text reveals with kinetic scrambling",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      scrambleDuration: 1.2,
    },
  },
  textScramble: {
    label: "Text Scramble",
    sublabel: "Random character scrambling animation",
    icon: "⚡",
    iconBg: "#2a1a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Text Scramble",
      subtext: "Characters scramble then reveal",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      scrambleChars: "!@#$%^&*",
      duration: 1,
    },
  },
  typewriterReveal: {
    label: "Typewriter Reveal",
    sublabel: "Character-by-character typing effect",
    icon: "⌨",
    iconBg: "#3a2a1a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Typewriter Text",
      subtext: "Type out character by character",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      typeSpeed: 50,
      showCursor: true,
    },
  },
  textMask: {
    label: "Text Mask",
    sublabel: "Text reveal with background image mask",
    icon: "🎭",
    iconBg: "#1a2a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Text Mask Reveal",
      subtext: "Image mask animates across text",
      fontSize: 3.5,
      fontWeight: 800,
      imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8e3a7f1f?w=800",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      maskDuration: 2,
    },
  },
  morphingCounter: {
    label: "Morphing Counter",
    sublabel: "Numbers animate with morphing effect",
    icon: "🔢",
    iconBg: "#2a1a1a",
    iconColor: "#CDFE00",
    defaultProps: {
      label: "Impressive Results",
      startValue: 0,
      endValue: 1500,
      suffix: "+",
      fontSize: 3,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#CDFE00",
      duration: 2,
    },
  },
  liquidText: {
    label: "Liquid Text",
    sublabel: "Text with liquid/blob distortion",
    icon: "💧",
    iconBg: "#1a3a1a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Liquid Motion",
      subtext: "Fluid, organic text distortion",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      distortionAmount: 2,
    },
  },
  waveText: {
    label: "Wave Text",
    sublabel: "Characters move in wave pattern",
    icon: "〰",
    iconBg: "#3a1a2a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Wave Motion",
      subtext: "Letters dance in a wave",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      waveHeight: 30,
      waveSpeed: 1.5,
    },
  },
  audioVisualizer: {
    label: "Audio Visualizer",
    sublabel: "Bars responding to sound or animation",
    icon: "🎵",
    iconBg: "#2a2a1a",
    iconColor: "#CDFE00",
    defaultProps: {
      label: "Sound Visualization",
      barCount: 20,
      barColor: "#CDFE00",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      animationMode: "auto",
      audioUrl: "",
    },
  },
  depthOfField: {
    label: "Depth of Field",
    sublabel: "Text with selective focus blur",
    icon: "🔍",
    iconBg: "#1a1a2a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Sharp Focus",
      subtext: "Foreground sharp, background blurred",
      fontSize: 3.5,
      fontWeight: 800,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      blurAmount: 8,
      focusIntensity: 0.7,
    },
  },
};

// Education Blocks
FB.blocks.EDUCATION_DEFS = {
  courseHero: {
    label: "Course Hero",
    sublabel: "Course intro with video",
    icon: "🎓",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      courseTitle: "Course Title",
      courseDescription: "Learn the fundamentals and advanced concepts in this comprehensive course.",
      instructorName: "Instructor Name",
      instructorTitle: "Course Creator",
      instructorImage: "",
      videoCover: "",
      videoUrl: "",
      duration: "8 hours",
      lessons: "24 lessons",
      level: "Beginner",
      price: "Free",
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  videoLesson: {
    label: "Video Lesson",
    sublabel: "Lesson with video and details",
    icon: "▶",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      lessonTitle: "Lesson Title",
      lessonNumber: "Lesson 1",
      videoUrl: "",
      duration: "12 min",
      difficulty: "Beginner",
      description: "In this lesson, you will learn...",
      learning_objectives: ["Objective 1", "Objective 2", "Objective 3"],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  moduleOverview: {
    label: "Module Overview",
    sublabel: "Module intro with lesson list",
    icon: "📚",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      moduleTitle: "Module 1: Fundamentals",
      moduleDescription: "Master the core concepts and foundational knowledge.",
      videoUrl: "",
      lessons: [
        { title: "Getting Started", duration: "8 min" },
        { title: "Key Concepts", duration: "15 min" },
        { title: "Practice Exercise", duration: "20 min" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  lessonNav: {
    label: "Lesson Navigation",
    sublabel: "Previous/Next and progress",
    icon: "◄ ►",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      currentLesson: "Lesson 5: Advanced Techniques",
      progress: 42,
      totalLessons: 24,
      previousLesson: "Lesson 4: Basic Techniques",
      nextLesson: "Lesson 6: Troubleshooting",
      completedLessons: 10,
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  videoTranscript: {
    label: "Video + Transcript",
    sublabel: "Video with searchable transcript",
    icon: "📝",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      videoUrl: "",
      transcript: "Lesson transcript text goes here. This is searchable and scrollable with timestamps.",
      timestamps: [
        { time: "0:00", text: "Introduction" },
        { time: "2:30", text: "Main topic" },
        { time: "8:45", text: "Key points" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  videoResources: {
    label: "Video + Resources",
    sublabel: "Video with downloadables",
    icon: "📥",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      lessonTitle: "Lesson Title",
      videoUrl: "",
      resources: [
        { name: "Lesson Notes", url: "#", type: "PDF" },
        { name: "Code Examples", url: "#", type: "ZIP" },
        { name: "Resources", url: "#", type: "Link" },
      ],
      relatedLinks: [
        { text: "Official Documentation", url: "#" },
        { text: "Community Forum", url: "#" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  videoChapters: {
    label: "Video Chapters",
    sublabel: "Video with chapter navigation",
    icon: "⏱",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      videoUrl: "",
      chapters: [
        { timestamp: 0, title: "Introduction" },
        { timestamp: 120, title: "Main Topic Part 1" },
        { timestamp: 480, title: "Main Topic Part 2" },
        { timestamp: 780, title: "Conclusion" },
      ],
      duration: "15:30",
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  quizBlock: {
    label: "Quiz/Assessment",
    sublabel: "Questions and answers",
    icon: "❓",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      quizTitle: "Knowledge Check",
      instructions: "Answer the following questions to test your knowledge.",
      questions: [
        { question: "Question 1?", answers: ["Answer A", "Answer B", "Answer C"], correct: 0 },
        { question: "Question 2?", answers: ["Answer A", "Answer B", "Answer C"], correct: 1 },
      ],
      passingScore: 70,
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  instructorBio: {
    label: "Instructor Bio",
    sublabel: "Instructor profile with video",
    icon: "👤",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      instructorName: "Instructor Name",
      title: "Expert Trainer",
      bio: "Experienced instructor with 10+ years of expertise.",
      image: "",
      videoUrl: "",
      expertise: ["JavaScript", "React", "Web Design"],
      social: [
        { platform: "Twitter", url: "#" },
        { platform: "LinkedIn", url: "#" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  curriculum: {
    label: "Curriculum Outline",
    sublabel: "Complete course structure",
    icon: "📋",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      courseName: "Course Name",
      modules: [
        { title: "Module 1", lessons: 5, duration: "2 hours" },
        { title: "Module 2", lessons: 6, duration: "2.5 hours" },
        { title: "Module 3", lessons: 4, duration: "1.5 hours" },
      ],
      totalDuration: "6 hours",
      totalLessons: 15,
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  objectives: {
    label: "Learning Objectives",
    sublabel: "Goals and outcomes",
    icon: "✓",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      title: "What You'll Learn",
      objectives: [
        "Understand core concepts and fundamentals",
        "Apply techniques in real-world projects",
        "Solve complex problems with confidence",
        "Build professional-quality solutions",
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  progressTracker: {
    label: "Progress Tracker",
    sublabel: "Course completion status",
    icon: "📊",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      completed: 12,
      total: 24,
      percentage: 50,
      recentLessons: [
        "Lesson 1: Complete",
        "Lesson 2: Complete",
        "Lesson 3: In Progress",
      ],
      estimatedCompletion: "5 days",
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  certificate: {
    label: "Certificate Block",
    sublabel: "Completion certificate",
    icon: "🏆",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      studentName: "Student Name",
      courseName: "Course Name",
      completionDate: "May 30, 2026",
      certificateNumber: "CERT-2026-12345",
      instructorName: "Instructor Name",
      status: "Completed",
      showCertificate: true,
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  comments: {
    label: "Video Comments",
    sublabel: "Discussion section",
    icon: "💬",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      enableComments: true,
      comments: [
        { author: "Student Name", text: "Great lesson!", date: "2 days ago" },
        { author: "Another Student", text: "Very helpful!", date: "1 day ago" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
  relatedContent: {
    label: "Related Content",
    sublabel: "Suggested next lessons",
    icon: "🔗",
    iconBg: "#1e40af",
    iconColor: "#93c5fd",
    defaultProps: {
      title: "Up Next",
      relatedLessons: [
        { title: "Next Lesson", duration: "12 min", status: "locked" },
        { title: "Advanced Topic", duration: "18 min", status: "locked" },
        { title: "Practice Project", duration: "30 min", status: "locked" },
      ],
      suggestedCourses: [
        { title: "Advanced Course", price: "Free" },
        { title: "Specialized Path", price: "Paid" },
      ],
      bg: "#0f172a",
      textColor: "#f1f5f9",
      accentColor: "#3b82f6",
    },
  },
};

// Normalize all blocks to include advanced properties
FB.blocks.ADVANCED_DEFAULTS = {
  // Custom HTML/CSS
  _customClass: "",
  _customId: "",
  _dataAttributes: "",
  _customAttributes: "",

  // Animations
  _animationType: "none",
  _animDuration: 500,
  _animDelay: 0,
  _animEasing: "ease",
  _exitAnimation: "none",
  _exitDuration: 500,
  _exitDelay: 0,

  // Interactions
  _onClickAction: "none",
  _onClickValue: "",
  _onClickNewTab: false,
  _onHoverEffect: "none",
  _onHoverIntensity: 1,
  _onScrollTrigger: "none",
  _scrollOffset: 0,
  _scrollDuration: 800,

  // Advanced Styling
  _filter: "",
  _backdropFilter: "",
  _willChange: "auto",
  _perspective: "",
  _perspectiveOrigin: "",
  _clipPath: "",

  // Responsive Visibility
  _hideOnMobile: false,
  _hideOnTablet: false,
  _hideOnDesktop: false,
  _responsivePadding: {},
  _responsiveMargin: {},
  _responsiveFont: {},
  _responsiveWidth: {},

  // Accessibility
  _ariaLabel: "",
  _ariaDescribedBy: "",
  _ariaHidden: false,
  _role: "",
  _altText: "",
  _skipLink: false,
  _tabIndex: "auto",

  // Performance
  _lazyLoad: false,
  _lazyLoadPlaceholder: false,
  _preload: false,
  _fetchPriority: "auto",
  _deferImages: false,

  // Analytics & Tracking
  _trackingId: "",
  _trackingEvent: "",
  _trackingValue: "",
  _conversionPixel: "",
  _conversionLabel: "",
  _dataLayerObject: ""
};

FB.blocks.normalizeBlock = function(blockDef) {
  if (blockDef.defaultProps) {
    var key;
    for (key in FB.blocks.ADVANCED_DEFAULTS) {
      if (!(key in blockDef.defaultProps)) {
        blockDef.defaultProps[key] = FB.blocks.ADVANCED_DEFAULTS[key];
      }
    }
  }
  return blockDef;
};

FB.blocks.normalizeAllBlocks = function() {
  var key;
  for (key in FB.blocks.BLOCK_DEFS) {
    FB.blocks.normalizeBlock(FB.blocks.BLOCK_DEFS[key]);
  }
  for (key in FB.blocks.CUSTOM_BLOCK_DEFS) {
    FB.blocks.normalizeBlock(FB.blocks.CUSTOM_BLOCK_DEFS[key]);
  }
  for (key in FB.blocks.ECOMMERCE_DEFS) {
    FB.blocks.normalizeBlock(FB.blocks.ECOMMERCE_DEFS[key]);
  }
  for (key in FB.blocks.EDUCATION_DEFS) {
    FB.blocks.normalizeBlock(FB.blocks.EDUCATION_DEFS[key]);
  }
};
