FB.blocks = {};

FB.blocks.BLOCK_DEFS = {
  nav: {
    label: "Navigation",
    sublabel: "Logo + links + CTA",
    icon: "≡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Work", "Services", "About", "Contact"],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      menuStyle: "simple",
    },
  },
  hero: {
    label: "Hero",
    sublabel: "Full-screen opener",
    icon: "H",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Nottingham · Est. 2026",
      headline: "We build things that <em>matter.</em>",
      subtext:
        "Bold brand and web design for businesses that refuse to be ordinary.",
      ctaText: "See our work →",
      bg: "#111111",
      accentColor: "#CDFE00",
      showBlob: true,
      blobStyle: "blob",
    },
  },
  marquee: {
    label: "Marquee Strip",
    sublabel: "Scrolling keyword band",
    icon: "»»",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Award Winning",
        "Creative",
        "Results Driven",
        "Human Centred",
        "Boldly Different",
      ],
      bg: "#CDFE00",
      textColor: "#111111",
      speed: 16,
    },
  },
  work: {
    label: "Work Grid",
    sublabel: "5-card project showcase",
    icon: "⊞",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our work.",
      headline: "Selected projects.",
      cards: [
        {
          tag: "Fintech · Platform",
          title: "Project One",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
        },
        {
          tag: "SaaS · Brand",
          title: "Project Two",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
        },
        {
          tag: "E-commerce · UI",
          title: "Project Three",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
        },
        {
          tag: "Mobile · App",
          title: "Project Four",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
        },
        {
          tag: "Web · Strategy",
          title: "Project Five",
          bg: "linear-gradient(135deg,#1a1a1a,#3a3a3a)",
        },
      ],
      bg: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  services: {
    label: "Services List",
    sublabel: "Large text row layout",
    icon: "≫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Brand Strategy",
        "Web Design",
        "Development",
        "SEO & Growth",
        "Content Creation",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  stats: {
    label: "Stats Counter",
    sublabel: "Animated number counters",
    icon: "#",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      stats: [
        { value: 150, suffix: "+", label: "Projects Delivered" },
        { value: 98, suffix: "%", label: "Client Retention" },
        { value: 12, suffix: "", label: "Industry Awards" },
        { value: 5, suffix: "M+", label: "Revenue Generated" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  testimonial: {
    label: "Testimonial",
    sublabel: "Client quote + avatar",
    icon: '"',
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      quote:
        "They transformed our brand completely. The results speak for themselves — 3x more leads in just 60 days.",
      name: "Sarah Mitchell",
      role: "CEO, TechForward",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  process: {
    label: "Process Steps",
    sublabel: "Numbered workflow stages",
    icon: "①",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      steps: [
        {
          num: "01",
          title: "Discovery",
          desc: "We learn about your brand, goals, and audience.",
        },
        {
          num: "02",
          title: "Design",
          desc: "Bold concepts that stand out from the noise.",
        },
        {
          num: "03",
          title: "Build",
          desc: "Pixel-perfect development with clean code.",
        },
        {
          num: "04",
          title: "Launch",
          desc: "Go live with confidence and ongoing support.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cta: {
    label: "Call to Action",
    sublabel: "Bold conversion section",
    icon: "→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Ready to stand out?",
      subtext: "Let's build something extraordinary together.",
      btnText: "Start a project",
      bg: "#CDFE00",
      textColor: "#111111",
      accentColor: "#111111",
    },
  },
  footer: {
    label: "Footer",
    sublabel: "Links + social + copyright",
    icon: "▁",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      brandName: "YourBrand.",
      tagline: "Bold design for bold businesses.",
      columns: [
        {
          heading: "Services",
          links: ["Web Design", "Branding", "Development", "SEO"],
        },
        { heading: "Company", links: ["About", "Careers", "Blog", "Contact"] },
        { heading: "Legal", links: ["Privacy", "Terms", "Cookies"] },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  features: {
    label: "Features Grid",
    sublabel: "Icon + title + description cards",
    icon: "⚡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Why choose us",
      headline: "Built different.",
      features: [
        {
          icon: "⚡",
          title: "Lightning Fast",
          desc: "Optimized for speed and performance.",
        },
        {
          icon: "🎨",
          title: "Bold Design",
          desc: "Stand out from the competition.",
        },
        { icon: "📱", title: "Responsive", desc: "Perfect on every device." },
        { icon: "🔒", title: "Secure", desc: "Enterprise-grade security." },
        {
          icon: "📈",
          title: "SEO Ready",
          desc: "Built to rank on search engines.",
        },
        {
          icon: "🤝",
          title: "Support",
          desc: "Ongoing help when you need it.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  pricing: {
    label: "Pricing Table",
    sublabel: "3-tier pricing cards",
    icon: "$",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Pricing",
      headline: "Simple, transparent pricing.",
      plans: [
        {
          name: "Starter",
          price: "£999",
          period: "/project",
          features: [
            "5 pages",
            "Mobile responsive",
            "Basic SEO",
            "1 revision round",
          ],
          cta: "Get started",
          highlighted: false,
        },
        {
          name: "Professional",
          price: "£2,499",
          period: "/project",
          features: [
            "10 pages",
            "Mobile responsive",
            "Advanced SEO",
            "3 revision rounds",
            "Analytics setup",
            "CMS integration",
          ],
          cta: "Most popular",
          highlighted: true,
        },
        {
          name: "Enterprise",
          price: "£4,999",
          period: "/project",
          features: [
            "Unlimited pages",
            "Mobile responsive",
            "Full SEO suite",
            "Unlimited revisions",
            "Analytics setup",
            "Custom integrations",
            "Priority support",
          ],
          cta: "Contact us",
          highlighted: false,
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  team: {
    label: "Team Grid",
    sublabel: "Member photos + roles",
    icon: "👥",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our team",
      headline: "Meet the crew.",
      members: [
        {
          name: "Alex Chen",
          role: "Creative Director",
          imageUrl:
            "https://images.unsplash.com/photo-1507003211169-465903714315?w=400",
        },
        {
          name: "Sam Rivera",
          role: "Lead Developer",
          imageUrl:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
        },
        {
          name: "Jordan Lee",
          role: "UX Designer",
          imageUrl:
            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
        },
        {
          name: "Morgan Park",
          role: "Strategist",
          imageUrl:
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  videoHero: {
    label: "Video Hero",
    sublabel: "Background video opener",
    icon: "▶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We create digital experiences.",
      subtext: "Bold, immersive, and unforgettable.",
      ctaText: "Watch our showreel",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitHero: {
    label: "Split Hero",
    sublabel: "Text left, image right",
    icon: "◫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Welcome",
      headline: "Design that converts.",
      subtext:
        "We blend creativity with strategy to build websites that don't just look good — they perform.",
      ctaText: "See our work",
      imageUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  orbsHero: {
    label: "Orbs Hero",
    sublabel: "Animated gradient orbs",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We design for the bold.",
      subtext: "Not the safe. Not the ordinary. The bold.",
      ctaText: "Explore our work",
      bg: "#0a0a0a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  megaNav: {
    label: "Mega Navigation",
    sublabel: "Dropdown with columns",
    icon: "☰",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: [
        {
          label: "Services",
          columns: [
            {
              heading: "Design",
              items: ["Web Design", "Brand Identity", "UI/UX"],
            },
            { heading: "Build", items: ["Development", "CMS", "E-commerce"] },
          ],
        },
        { label: "Work", url: "#" },
        { label: "About", url: "#" },
        { label: "Contact", url: "#" },
      ],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  slideNav: {
    label: "Slide Navigation",
    sublabel: "Animated slide-in nav",
    icon: "⊳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Work", "Services", "About", "Blog", "Contact"],
      ctaText: "Let's talk",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  resultsGrid: {
    label: "Results Grid",
    sublabel: "Data-driven showcase",
    icon: "▦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Results",
      headline: "Numbers that speak.",
      items: [
        { value: "340%", label: "Average ROI" },
        { value: "2.1M", label: "Users Reached" },
        { value: "89", label: "Projects Live" },
        { value: "4.9★", label: "Client Rating" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  glassCards: {
    label: "Glass Cards",
    sublabel: "Frosted glass effect cards",
    icon: "◇",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "What we offer.",
      cards: [
        { title: "Brand Strategy", desc: "Define your voice and stand out." },
        { title: "Web Design", desc: "Beautiful, functional websites." },
        {
          title: "Growth Marketing",
          desc: "Data-driven campaigns that convert.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  portfolioGrid: {
    label: "Portfolio Grid",
    sublabel: "Masonry-style project gallery",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Portfolio",
      headline: "Selected work.",
      items: [
        {
          title: "Project Alpha",
          category: "Web Design",
          imageUrl:
            "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600",
        },
        {
          title: "Project Beta",
          category: "Branding",
          imageUrl:
            "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600",
        },
        {
          title: "Project Gamma",
          category: "E-commerce",
          imageUrl:
            "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  clientCarousel: {
    label: "Client Carousel",
    sublabel: "Scrolling logo strip",
    icon: "◎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Trusted by",
      clients: [
        "Acme Corp",
        "TechCo",
        "DesignLab",
        "StartupXYZ",
        "BrandHQ",
        "MediaPlus",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  trustPill: {
    label: "Trust Pill",
    sublabel: "Rating + verified badge",
    icon: "✓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      ratingText: "Google Reviews",
      verifiedDate: "Verified Business",
      ratingCount: 5,
      starColor: "#FFD700",
      bg: "#111111",
      textColor: "#f7f6f2",
    },
  },
  metricBox: {
    label: "Metric Box",
    sublabel: "Single stat highlight",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      value: "97%",
      label: "Client satisfaction rate",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  wordSwap: {
    label: "Word Swap",
    sublabel: "Animated text rotation",
    icon: "⟳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      prefix: "We build",
      words: ["brands", "websites", "experiences", "futures"],
      suffix: "that matter.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  chatWidget: {
    label: "Chat Widget",
    sublabel: "Floating chat bubble",
    icon: "💬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      greeting: "Hi! How can we help?",
      btnText: "Chat with us",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cookieConsent: {
    label: "Cookie Consent",
    sublabel: "GDPR cookie banner",
    icon: "🍪",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      message: "We use cookies to enhance your experience.",
      acceptText: "Accept All",
      declineText: "Decline",
      bg: "#1a1a1a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  liteVideo: {
    label: "Lite Video",
    sublabel: "Lazy-loaded video embed",
    icon: "🎬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      thumbnailUrl:
        "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      caption: "Our showreel 2026",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  faq: {
    label: "FAQ Accordion",
    sublabel: "Expandable Q&A section",
    icon: "?",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "FAQ",
      headline: "Common questions.",
      items: [
        {
          q: "How long does a project take?",
          a: "Typically 4-8 weeks depending on scope.",
        },
        {
          q: "Do you offer ongoing support?",
          a: "Yes, all plans include post-launch support.",
        },
        {
          q: "What's your pricing?",
          a: "Projects start at £999. Contact us for a quote.",
        },
        {
          q: "Can you work with existing brands?",
          a: "Absolutely — we adapt to your brand guidelines.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitText: {
    label: "Split Text",
    sublabel: "Character-by-character animation",
    icon: "Aa",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Animated text.",
      subtext: "Each character animates in on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  maskReveal: {
    label: "Mask Reveal",
    sublabel: "Clip-path reveal animation",
    icon: "▨",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Revealed on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  fullscreenMenu: {
    label: "Fullscreen Menu",
    sublabel: "Full-screen navigation overlay",
    icon: "⛶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      links: ["Home", "Work", "Services", "About", "Contact"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  circularList: {
    label: "Circular List",
    sublabel: "Rotating circular items",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: ["Design", "Build", "Launch", "Grow"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  glitchText: {
    label: "Glitch Text",
    sublabel: "RGB glitch effect",
    icon: "G",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "GLITCH.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  svgDraw: {
    label: "SVG Draw",
    sublabel: "Animated stroke drawing",
    icon: "✎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Drawn on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  dayNightSwitcher: {
    label: "Day/Night Switch",
    sublabel: "Theme toggle section",
    icon: "☀",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      dayText: "Day mode",
      nightText: "Night mode",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  particleButton: {
    label: "Particle Button",
    sublabel: "Hover particle effect CTA",
    icon: "✦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Hover me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  noiseSection: {
    label: "Noise Section",
    sublabel: "Film grain texture overlay",
    icon: "▒",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Textured.",
      subtext: "Film grain adds depth and character.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  scrollIndicator: {
    label: "Scroll Indicator",
    sublabel: "Animated scroll prompt",
    icon: "↓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      text: "Scroll to explore",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  timeline: {
    label: "Timeline",
    sublabel: "Vertical milestone layout",
    icon: "│",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Our journey.",
      events: [
        {
          year: "2020",
          title: "Founded",
          desc: "Started in a Nottingham garage.",
        },
        {
          year: "2022",
          title: "First office",
          desc: "Moved into our creative studio.",
        },
        {
          year: "2024",
          title: "50 clients",
          desc: "Hit our biggest milestone yet.",
        },
        {
          year: "2026",
          title: "Going global",
          desc: "Expanding to international markets.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  iridescentBtn: {
    label: "Iridescent Button",
    sublabel: "Holographic gradient CTA",
    icon: "◈",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Click me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  counterSection: {
    label: "Counter Section",
    sublabel: "Animated counting numbers",
    icon: "0→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      counters: [
        { target: 500, suffix: "+", label: "Happy clients" },
        { target: 1200, suffix: "+", label: "Projects done" },
        { target: 15, suffix: "", label: "Team members" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cornerSection: {
    label: "Corner Section",
    sublabel: "Decorative corner borders",
    icon: "┌",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Framed.",
      subtext: "Corner accents add editorial polish.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  horizontalScroll: {
    label: "Horizontal Scroll",
    sublabel: "Side-scrolling card track",
    icon: "⇉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Featured",
      headline: "Latest work.",
      cards: [
        {
          category: "Fintech",
          title: "Project One",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
        },
        {
          category: "SaaS",
          title: "Project Two",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
        },
        {
          category: "E-commerce",
          title: "Project Three",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
        },
        {
          category: "Mobile",
          title: "Project Four",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
};

FB.blocks.CUSTOM_BLOCK_DEFS = {
  textBlock: {
    label: "Custom Text",
    sublabel: "Heading + paragraph",
    icon: "T",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Your Headline Here",
      body: "Your body text goes here. Click to edit inline, or use the style panel on the right to change colours and spacing.",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#CDFE00",
      paddingV: 64,
      paddingH: 48,
    },
  },
  colorBlock: {
    label: "Colour Block",
    sublabel: "Full-width colour section",
    icon: "■",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Bold Statement.",
      body: "A full-colour section for emphasis.",
      bg: "#CDFE00",
      textColor: "#111111",
      paddingV: 80,
      paddingH: 48,
    },
  },
  imageTextTop: {
    label: "Image + Text (Top)",
    sublabel: "Image above text",
    icon: "◰",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that describes the image above. Click to edit any content.",
      imageUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      imageAlt: "Section image",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 0,
      imagePosition: "top",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextBottom: {
    label: "Image + Text (Bottom)",
    sublabel: "Text above image",
    icon: "◳",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that introduces the image below.",
      imageUrl:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800",
      imageAlt: "Team collaboration",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 12,
      imagePosition: "bottom",
      textAlign: "center",
      bg: "#f8fafc",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextLeft: {
    label: "Image + Text (Left)",
    sublabel: "Image left, text right",
    icon: "◧",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Great for feature descriptions or about sections.",
      imageUrl:
        "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600",
      imageAlt: "Feature showcase",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "left",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
  imageTextRight: {
    label: "Image + Text (Right)",
    sublabel: "Text left, image right",
    icon: "◨",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Perfect for testimonials or case studies.",
      imageUrl:
        "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600",
      imageAlt: "Case study",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "right",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
};

FB.blocks.ECOMMERCE_DEFS = {
  ecomProductCard: {
    label: "Product Card",
    sublabel: "Image + price + cart button",
    icon: "🛒",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
      title: "Premium Watch",
      price: "£129.00",
      salePrice: "",
      rating: 4,
      reviewCount: 24,
      btnText: "Add to Cart",
      badge: "",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductGrid: {
    label: "Product Grid",
    sublabel: "Multi-column product layout",
    icon: "⊞",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      columns: 3,
      gap: 24,
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Premium Watch",
          price: "£129.00",
          salePrice: "",
          rating: 4,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Wireless Headphones",
          price: "£89.00",
          salePrice: "£69.00",
          rating: 5,
          badge: "Sale",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Sunglasses",
          price: "£45.00",
          salePrice: "",
          rating: 3,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Leather Boots",
          price: "£199.00",
          salePrice: "",
          rating: 5,
          badge: "New",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
          title: "Perfume",
          price: "£75.00",
          salePrice: "",
          rating: 4,
          badge: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
          title: "Backpack",
          price: "£110.00",
          salePrice: "£85.00",
          rating: 4,
          badge: "Sale",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomFeaturedProduct: {
    label: "Featured Product",
    sublabel: "Split layout with details",
    icon: "★",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
      title: "Premium Chronograph Watch",
      description:
        "Handcrafted stainless steel timepiece with sapphire crystal glass. Water resistant to 100m. Swiss automatic movement with 42-hour power reserve.",
      price: "£349.00",
      salePrice: "£279.00",
      variants: "Black / Silver / Rose Gold",
      btnText: "Add to Cart",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductCarousel: {
    label: "Product Carousel",
    sublabel: "Scrollable product strip",
    icon: "⟳",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      cardsVisible: 4,
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Watch",
          price: "£129.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Headphones",
          price: "£89.00",
          salePrice: "£69.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Sunglasses",
          price: "£45.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Boots",
          price: "£199.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=400",
          title: "Perfume",
          price: "£75.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
          title: "Backpack",
          price: "£110.00",
          salePrice: "£85.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400",
          title: "Smart Watch",
          price: "£249.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=400",
          title: "Sneakers",
          price: "£135.00",
          salePrice: "",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomQuickView: {
    label: "Quick View",
    sublabel: "Modal product preview",
    icon: "👁",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      triggerText: "Quick View Product",
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600",
      title: "Premium Watch",
      price: "£129.00",
      salePrice: "",
      description: "Click to open a modal quick-view of this product.",
      btnText: "Add to Cart",
      modalBg: "#1a1a1a",
      overlayOpacity: 0.8,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomCartDrawer: {
    label: "Cart Drawer",
    sublabel: "Slide-in cart panel",
    icon: "🛍",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      emptyText: "Your cart is empty",
      checkoutBtnText: "Checkout",
      bg: "#1a1a1a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCartSummary: {
    label: "Cart Summary",
    sublabel: "Subtotal + tax + total",
    icon: "Σ",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      shippingText: "Shipping",
      taxRate: 20,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCheckoutForm: {
    label: "Checkout Form",
    sublabel: "Billing + order summary",
    icon: "📋",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      heading: "Checkout",
      btnText: "Place Order",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomSaleBanner: {
    label: "Sale Banner",
    sublabel: "Discount announcement strip",
    icon: "🔥",
    iconBg: "#ef4444",
    iconColor: "#fff",
    defaultProps: {
      headline: "SUMMER SALE",
      subtext: "Up to 50% off selected items",
      btnText: "Shop Now",
      btnUrl: "#",
      bg: "#ef4444",
      textColor: "#ffffff",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomCountdown: {
    label: "Countdown Timer",
    sublabel: "Days / hours / mins / secs",
    icon: "⏱",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Sale Ends In",
      targetDate: "2026-06-01T00:00:00",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomCouponInput: {
    label: "Coupon Input",
    sublabel: "Promo code field",
    icon: "🏷",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Have a promo code?",
      placeholder: "Enter code here",
      btnText: "Apply",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomShippingProgress: {
    label: "Shipping Progress",
    sublabel: "Free shipping threshold bar",
    icon: "📦",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      threshold: 50,
      currentAmount: 32,
      headline: "Free shipping on orders over £50",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomReviews: {
    label: "Product Reviews",
    sublabel: "Star ratings + review cards",
    icon: "⭐",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      rating: 4.7,
      reviewCount: 128,
      reviews: [
        {
          name: "Sarah M.",
          rating: 5,
          date: "2 days ago",
          text: "Absolutely love this product! Quality is outstanding and delivery was super fast.",
        },
        {
          name: "James T.",
          rating: 4,
          date: "1 week ago",
          text: "Great value for money. Would recommend to anyone looking for a reliable option.",
        },
        {
          name: "Emma L.",
          rating: 5,
          date: "2 weeks ago",
          text: "Exceeded my expectations. The attention to detail is remarkable.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomFilters: {
    label: "Filters & Sort",
    sublabel: "Category, price, sort controls",
    icon: "⚙",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      categories: ["All", "Clothing", "Accessories", "Footwear", "Electronics"],
      sortOptions: [
        "Featured",
        "Price: Low to High",
        "Price: High to Low",
        "Newest",
        "Best Rating",
      ],
      showPriceRange: true,
      showGridToggle: true,
      resultsText: "24 products found",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomTrustBadges: {
    label: "Trust Badges",
    sublabel: "Secure checkout, returns, warranty icons",
    icon: "🛡",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      badges: [
        {
          icon: "🔒",
          title: "Secure Checkout",
          desc: "256-bit SSL encryption",
        },
        { icon: "🔄", title: "Free Returns", desc: "30-day return policy" },
        { icon: "🚚", title: "Free Shipping", desc: "Orders over £50" },
        { icon: "⭐", title: "Top Rated", desc: "4.9/5 from 2,000+ reviews" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomNewsletter: {
    label: "Newsletter Signup",
    sublabel: "Email capture with discount offer",
    icon: "✉",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      headline: "Get 10% Off Your First Order",
      subtext:
        "Join our mailing list for exclusive deals, new arrivals, and style inspiration.",
      placeholder: "Enter your email",
      btnText: "Subscribe",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  ecomRelatedProducts: {
    label: "Related Products",
    sublabel: "You might also like section",
    icon: "🔗",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      heading: "You Might Also Like",
      products: [
        {
          imageUrl:
            "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400",
          title: "Classic Watch",
          price: "£129.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
          title: "Wireless Earbuds",
          price: "£89.00",
          salePrice: "£69.00",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
          title: "Aviator Sunglasses",
          price: "£45.00",
          salePrice: "",
        },
        {
          imageUrl:
            "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=400",
          title: "Leather Wallet",
          price: "£59.00",
          salePrice: "",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      saleColor: "#ef4444",
    },
  },
  ecomProductTabs: {
    label: "Product Tabs",
    sublabel: "Description / Specs / Reviews tabs",
    icon: "📑",
    iconBg: "#3a3a3a",
    iconColor: "#CDFE00",
    defaultProps: {
      tabs: [
        {
          label: "Description",
          content:
            "<p>Our premium collection features handcrafted materials with attention to every detail. Each piece is designed to combine style with functionality, ensuring you look your best while enjoying lasting quality.</p><p>Features include premium materials, expert craftsmanship, and a satisfaction guarantee.</p>",
        },
        {
          label: "Specifications",
          content:
            "<table><tr><td>Material</td><td>Premium Stainless Steel</td></tr><tr><td>Weight</td><td>120g</td></tr><tr><td>Dimensions</td><td>42mm × 12mm</td></tr><tr><td>Water Resistance</td><td>100m / 10 ATM</td></tr><tr><td>Warranty</td><td>2 Years</td></tr></table>",
        },
        {
          label: "Shipping",
          content:
            "<p><strong>Standard Shipping:</strong> 3-5 business days — £4.99</p><p><strong>Express Shipping:</strong> 1-2 business days — £9.99</p><p><strong>Free Shipping:</strong> On orders over £50</p><p>International shipping available to 40+ countries.</p>",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
};
