FB.blocks = {};

FB.blocks.BLOCK_DEFS = {
  nav: {
    label: "Navigation",
    sublabel: "Logo + links + CTA",
    icon: "≡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      logoImage: "",
      links: ["Work", "Services", "About", "Contact"],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      menuStyle: "simple",
    },
  },
  hero: {
    label: "Hero",
    sublabel: "Full-screen opener",
    icon: "H",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Nottingham · Est. 2026",
      headline: "We build things that <em>matter.</em>",
      subtext:
        "Bold brand and web design for businesses that refuse to be ordinary.",
      ctaText: "See our work →",
      bg: "#111111",
      accentColor: "#CDFE00",
      showBlob: true,
      blobStyle: "blob",
    },
  },
  marquee: {
    label: "Marquee Strip",
    sublabel: "Scrolling keyword band",
    icon: "»»",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Award Winning",
        "Creative",
        "Results Driven",
        "Human Centred",
        "Boldly Different",
      ],
      bg: "#CDFE00",
      textColor: "#111111",
      speed: 16,
    },
  },
  work: {
    label: "Work Grid",
    sublabel: "5-card project showcase",
    icon: "⊞",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our work.",
      headline: "Selected projects.",
      cards: [
        {
          tag: "Fintech · Platform",
          title: "Project One",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
        },
        {
          tag: "SaaS · Brand",
          title: "Project Two",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
        },
        {
          tag: "E-commerce · UI",
          title: "Project Three",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
        },
        {
          tag: "Mobile · App",
          title: "Project Four",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
        },
        {
          tag: "Web · Strategy",
          title: "Project Five",
          bg: "linear-gradient(135deg,#1a1a1a,#3a3a3a)",
        },
      ],
      bg: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  services: {
    label: "Services List",
    sublabel: "Large text row layout",
    icon: "≫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: [
        "Brand Strategy",
        "Web Design",
        "Development",
        "SEO & Growth",
        "Content Creation",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  stats: {
    label: "Stats Counter",
    sublabel: "Animated number counters",
    icon: "#",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      stats: [
        { value: 150, suffix: "+", label: "Projects Delivered" },
        { value: 98, suffix: "%", label: "Client Retention" },
        { value: 12, suffix: "", label: "Industry Awards" },
        { value: 5, suffix: "M+", label: "Revenue Generated" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  testimonial: {
    label: "Testimonial",
    sublabel: "Client quote + avatar",
    icon: '"',
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      quote:
        "They transformed our brand completely. The results speak for themselves — 3x more leads in just 60 days.",
      name: "Sarah Mitchell",
      role: "CEO, TechForward",
      avatarUrl:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  process: {
    label: "Process Steps",
    sublabel: "Numbered workflow stages",
    icon: "①",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      steps: [
        {
          num: "01",
          title: "Discovery",
          desc: "We learn about your brand, goals, and audience.",
        },
        {
          num: "02",
          title: "Design",
          desc: "Bold concepts that stand out from the noise.",
        },
        {
          num: "03",
          title: "Build",
          desc: "Pixel-perfect development with clean code.",
        },
        {
          num: "04",
          title: "Launch",
          desc: "Go live with confidence and ongoing support.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cta: {
    label: "Call to Action",
    sublabel: "Bold conversion section",
    icon: "→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Ready to stand out?",
      subtext: "Let's build something extraordinary together.",
      btnText: "Start a project",
      bg: "#CDFE00",
      textColor: "#111111",
      accentColor: "#111111",
    },
  },
  footer: {
    label: "Footer",
    sublabel: "Links + social + copyright",
    icon: "▁",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      brandName: "YourBrand.",
      tagline: "Bold design for bold businesses.",
      columns: [
        {
          heading: "Services",
          links: ["Web Design", "Branding", "Development", "SEO"],
        },
        { heading: "Company", links: ["About", "Careers", "Blog", "Contact"] },
        { heading: "Legal", links: ["Privacy", "Terms", "Cookies"] },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  features: {
    label: "Features Grid",
    sublabel: "Icon + title + description cards",
    icon: "⚡",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Why choose us",
      headline: "Built different.",
      features: [
        {
          icon: "⚡",
          title: "Lightning Fast",
          desc: "Optimized for speed and performance.",
        },
        {
          icon: "🎨",
          title: "Bold Design",
          desc: "Stand out from the competition.",
        },
        { icon: "📱", title: "Responsive", desc: "Perfect on every device." },
        { icon: "🔒", title: "Secure", desc: "Enterprise-grade security." },
        {
          icon: "📈",
          title: "SEO Ready",
          desc: "Built to rank on search engines.",
        },
        {
          icon: "🤝",
          title: "Support",
          desc: "Ongoing help when you need it.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  pricing: {
    label: "Pricing Table",
    sublabel: "3-tier pricing cards",
    icon: "$",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Pricing",
      headline: "Simple, transparent pricing.",
      plans: [
        {
          name: "Starter",
          price: "£999",
          period: "/project",
          features: [
            "5 pages",
            "Mobile responsive",
            "Basic SEO",
            "1 revision round",
          ],
          cta: "Get started",
          highlighted: false,
        },
        {
          name: "Professional",
          price: "£2,499",
          period: "/project",
          features: [
            "10 pages",
            "Mobile responsive",
            "Advanced SEO",
            "3 revision rounds",
            "Analytics setup",
            "CMS integration",
          ],
          cta: "Most popular",
          highlighted: true,
        },
        {
          name: "Enterprise",
          price: "£4,999",
          period: "/project",
          features: [
            "Unlimited pages",
            "Mobile responsive",
            "Full SEO suite",
            "Unlimited revisions",
            "Analytics setup",
            "Custom integrations",
            "Priority support",
          ],
          cta: "Contact us",
          highlighted: false,
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  team: {
    label: "Team Grid",
    sublabel: "Member photos + roles",
    icon: "👥",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Our team",
      headline: "Meet the crew.",
      members: [
        {
          name: "Alex Chen",
          role: "Creative Director",
          imageUrl:
            "https://images.unsplash.com/photo-1507003211169-465903714315?w=400",
        },
        {
          name: "Sam Rivera",
          role: "Lead Developer",
          imageUrl:
            "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400",
        },
        {
          name: "Jordan Lee",
          role: "UX Designer",
          imageUrl:
            "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400",
        },
        {
          name: "Morgan Park",
          role: "Strategist",
          imageUrl:
            "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  videoHero: {
    label: "Video Hero",
    sublabel: "Background video opener",
    icon: "▶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We create digital experiences.",
      subtext: "Bold, immersive, and unforgettable.",
      ctaText: "Watch our showreel",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitHero: {
    label: "Split Hero",
    sublabel: "Text left, image right",
    icon: "◫",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      eyebrow: "Welcome",
      headline: "Design that converts.",
      subtext:
        "We blend creativity with strategy to build websites that don't just look good — they perform.",
      ctaText: "See our work",
      embedUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      embedType: "image",
      imageAlt: "",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  orbsHero: {
    label: "Orbs Hero",
    sublabel: "Animated gradient orbs",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "We design for the bold.",
      subtext: "Not the safe. Not the ordinary. The bold.",
      ctaText: "Explore our work",
      bg: "#0a0a0a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  megaNav: {
    label: "Mega Navigation",
    sublabel: "Dropdown with columns",
    icon: "☰",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      logoImage: "",
      links: [
        {
          label: "Services",
          columns: [
            {
              heading: "Design",
              items: ["Web Design", "Brand Identity", "UI/UX"],
            },
            { heading: "Build", items: ["Development", "CMS", "E-commerce"] },
          ],
        },
        { label: "Work", url: "#" },
        { label: "About", url: "#" },
        { label: "Contact", url: "#" },
      ],
      ctaText: "Start a project",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  slideNav: {
    label: "Slide Navigation",
    sublabel: "Animated slide-in nav",
    icon: "⊳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      logoImage: "",
      links: ["Work", "Services", "About", "Blog", "Contact"],
      ctaText: "Let's talk",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  resultsGrid: {
    label: "Results Grid",
    sublabel: "Data-driven showcase",
    icon: "▦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Results",
      headline: "Numbers that speak.",
      items: [
        { value: "340%", label: "Average ROI" },
        { value: "2.1M", label: "Users Reached" },
        { value: "89", label: "Projects Live" },
        { value: "4.9★", label: "Client Rating" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  glassCards: {
    label: "Glass Cards",
    sublabel: "Frosted glass effect cards",
    icon: "◇",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "What we offer.",
      cards: [
        { title: "Brand Strategy", desc: "Define your voice and stand out." },
        { title: "Web Design", desc: "Beautiful, functional websites." },
        {
          title: "Growth Marketing",
          desc: "Data-driven campaigns that convert.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  portfolioGrid: {
    label: "Portfolio Grid",
    sublabel: "Masonry-style project gallery",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Portfolio",
      headline: "Selected work.",
      items: [
        {
          title: "Project Alpha",
          category: "Web Design",
          imageUrl:
            "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600",
        },
        {
          title: "Project Beta",
          category: "Branding",
          imageUrl:
            "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600",
        },
        {
          title: "Project Gamma",
          category: "E-commerce",
          imageUrl:
            "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  clientCarousel: {
    label: "Client Carousel",
    sublabel: "Scrolling logo strip",
    icon: "◎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Trusted by leading brands",
      clients: [
        "Acme Corp",
        "TechCo",
        "DesignLab",
        "StartupXYZ",
        "BrandHQ",
        "MediaPlus",
        "NovaCo",
        "Apex Studio",
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      style: "pill",
      mode: "marquee",
      twoRows: false,
      speed: 30,
      separator: "✦",
      fontSize: 14,
      gap: 24,
      showLabel: true,
      paddingV: 48,
    },
  },
  trustPill: {
    label: "Trust Pill",
    sublabel: "Rating + verified badge",
    icon: "✓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      ratingText: "Google Reviews",
      verifiedDate: "Verified Business",
      ratingCount: 5,
      starColor: "#FFD700",
      bg: "#111111",
      textColor: "#f7f6f2",
    },
  },
  metricBox: {
    label: "Metric Box",
    sublabel: "Single stat highlight",
    icon: "▣",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      value: "97%",
      label: "Client satisfaction rate",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  wordSwap: {
    label: "Word Swap",
    sublabel: "Animated text rotation",
    icon: "⟳",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      prefix: "We build",
      words: ["brands", "websites", "experiences", "futures"],
      suffix: "that matter.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  chatWidget: {
    label: "Chat Widget",
    sublabel: "Floating chat bubble",
    icon: "💬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      greeting: "Hi! How can we help?",
      btnText: "Chat with us",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  cookieConsent: {
    label: "Cookie Consent",
    sublabel: "GDPR cookie banner",
    icon: "🍪",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      title: "🍪 Cookies",
      message: "We use cookies to enhance your experience.",
      acceptText: "Accept All",
      declineText: "Decline",
      customizeText: "Customize",
      bg: "#1a1a1a",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      categories: [
        {
          id: "functional",
          name: "Functional",
          description: "Essential for the site to function properly.",
          required: true,
        },
        {
          id: "analytics",
          name: "Analytics",
          description: "Help us understand how visitors use the site.",
          required: false,
        },
        {
          id: "marketing",
          name: "Marketing",
          description: "Used to deliver relevant ads and content.",
          required: false,
        },
      ],
    },
  },
  liteVideo: {
    label: "Lite Video",
    sublabel: "Lazy-loaded video embed",
    icon: "🎬",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      thumbnailUrl:
        "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=800",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      caption: "Our showreel 2026",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  faq: {
    label: "FAQ Accordion",
    sublabel: "Expandable Q&A section",
    icon: "?",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "FAQ",
      headline: "Common questions.",
      items: [
        {
          q: "How long does a project take?",
          a: "Typically 4-8 weeks depending on scope.",
        },
        {
          q: "Do you offer ongoing support?",
          a: "Yes, all plans include post-launch support.",
        },
        {
          q: "What's your pricing?",
          a: "Projects start at £999. Contact us for a quote.",
        },
        {
          q: "Can you work with existing brands?",
          a: "Absolutely — we adapt to your brand guidelines.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  splitText: {
    label: "Split Text",
    sublabel: "Character-by-character animation",
    icon: "Aa",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Animated text.",
      subtext: "Each character animates in on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  maskReveal: {
    label: "Mask Reveal",
    sublabel: "Clip-path reveal animation",
    icon: "▨",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Revealed on scroll.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  fullscreenMenu: {
    label: "Fullscreen Menu",
    sublabel: "Full-screen navigation overlay",
    icon: "⛶",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      logoText: "YourBrand.",
      logoImage: "",
      links: ["Home", "Work", "Services", "About", "Contact"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  circularList: {
    label: "Circular List",
    sublabel: "Rotating circular items",
    icon: "◉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      items: ["Design", "Develop", "Deploy", "Grow", "Optimise", "Scale"],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      label: "How we work",
      centerText: "6",
      centerSubtext: "steps",
      mode: "ring",
      itemStyle: "pill",
      ringSize: 320,
      showConnectors: true,
      autoRotate: false,
      rotateSpeed: 25,
      glowItems: false,
      showNumbers: true,
      fontSize: 12,
      paddingV: 80,
      ringBorder: true,
      multiColor: false,
    },
  },
  glitchText: {
    label: "Glitch Text",
    sublabel: "RGB glitch effect",
    icon: "G",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "GLITCH.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  svgDraw: {
    label: "SVG Draw",
    sublabel: "Animated stroke drawing",
    icon: "✎",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Drawn on scroll.",
      subtext: "Scroll down to animate the stroke.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      animDuration: 3,
    },
  },
  dayNightSwitcher: {
    label: "Day/Night Switch",
    sublabel: "Theme toggle section",
    icon: "☀",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      dayText: "Day mode",
      nightText: "Night mode",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  particleButton: {
    label: "Particle Button",
    sublabel: "Hover particle effect CTA",
    icon: "✦",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Hover me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  noiseSection: {
    label: "Noise Section",
    sublabel: "Film grain texture overlay",
    icon: "▒",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Textured.",
      subtext: "Film grain adds depth and character.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  scrollIndicator: {
    label: "Scroll Indicator",
    sublabel: "Animated scroll prompt",
    icon: "↓",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      text: "Scroll to explore",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  timeline: {
    label: "Timeline",
    sublabel: "Vertical milestone layout",
    icon: "│",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Our journey.",
      events: [
        {
          year: "2020",
          title: "Founded",
          desc: "Started in a Nottingham garage.",
        },
        {
          year: "2022",
          title: "First office",
          desc: "Moved into our creative studio.",
        },
        {
          year: "2024",
          title: "50 clients",
          desc: "Hit our biggest milestone yet.",
        },
        {
          year: "2026",
          title: "Going global",
          desc: "Expanding to international markets.",
        },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  iridescentBtn: {
    label: "Iridescent Button",
    sublabel: "Holographic gradient CTA",
    icon: "◈",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      btnText: "Click me",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  counterSection: {
    label: "Counter Section",
    sublabel: "Animated counting numbers",
    icon: "0→",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      counters: [
        { target: 500, suffix: "+", label: "Happy clients" },
        { target: 1200, suffix: "+", label: "Projects done" },
        { target: 15, suffix: "", label: "Team members" },
      ],
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  socialLinks: {
    label: "Social Links",
    sublabel: "Multi-platform social hub",
    icon: "◎",
    iconBg: "#1a0a1e",
    iconColor: "#ec4899",
    defaultProps: {
      label: "Follow the Journey",
      headline: "Stay connected.",
      style: "cards",
      showHandles: true,
      showFollowers: true,
      showLabel: true,
      usePlatformColors: true,
      gap: 16,
      paddingV: 80,
      columns: 3,
      bg: "#0a0a0f",
      textColor: "#f7f6f2",
      accentColor: "#ec4899",
      networks: [
        {
          platform: "instagram",
          handle: "@yourbrand",
          followers: "12.4K",
          url: "#",
        },
        {
          platform: "twitter",
          handle: "@yourbrand",
          followers: "8.2K",
          url: "#",
        },
        {
          platform: "tiktok",
          handle: "@yourbrand",
          followers: "45.1K",
          url: "#",
        },
        {
          platform: "youtube",
          handle: "Your Brand",
          followers: "3.1K",
          url: "#",
        },
        {
          platform: "linkedin",
          handle: "Your Brand",
          followers: "2.8K",
          url: "#",
        },
        {
          platform: "github",
          handle: "yourbrand",
          followers: "1.2K",
          url: "#",
        },
      ],
    },
  },
  whatsappWidget: {
    label: "WhatsApp Connect",
    sublabel: "Direct WhatsApp CTA",
    icon: "✆",
    iconBg: "#0a1f0d",
    iconColor: "#25D366",
    defaultProps: {
      phone: "+447700000000",
      message: "Hi! I'd love to find out more about your services.",
      style: "card",
      label: "Chat with us",
      subtext: "Typically replies within minutes",
      buttonText: "Start a conversation",
      showStatus: true,
      statusText: "Online now",
      avatarBg: "#128C7E",
      bg: "#0a0a0a",
      textColor: "#f7f6f2",
      accentColor: "#25D366",
      paddingV: 64,
    },
  },
  cornerSection: {
    label: "Corner Section",
    sublabel: "Decorative corner borders",
    icon: "┌",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      headline: "Framed.",
      subtext: "Corner accents add editorial polish.",
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
    },
  },
  horizontalScroll: {
    label: "Horizontal Scroll",
    sublabel: "Side-scrolling card gallery",
    icon: "⇉",
    iconBg: "#3a3a3a",
    iconColor: "#d0d0d0",
    defaultProps: {
      label: "Featured Work",
      headline: "Projects that move.",
      subtext: "Drag or use arrows to explore",
      mode: "cards",
      cardStyle: "gradient",
      cardWidth: 320,
      showNumbers: true,
      showProgress: true,
      showArrows: true,
      showSubtitle: true,
      showTags: true,
      gap: 24,
      paddingV: 80,
      bg: "#111111",
      textColor: "#f7f6f2",
      accentColor: "#CDFE00",
      cards: [
        {
          category: "Fintech",
          title: "Project One",
          subtitle: "Brand identity & product design",
          tag: "2024",
          bg: "linear-gradient(135deg,#0d2137,#1a4a6e)",
        },
        {
          category: "SaaS",
          title: "Project Two",
          subtitle: "Full-stack web application",
          tag: "2024",
          bg: "linear-gradient(135deg,#1a1a3e,#3a1a5e)",
        },
        {
          category: "E-commerce",
          title: "Project Three",
          subtitle: "Conversion-focused redesign",
          tag: "2023",
          bg: "linear-gradient(135deg,#1a3a1a,#2e6e2e)",
        },
        {
          category: "Mobile",
          title: "Project Four",
          subtitle: "iOS & Android experience",
          tag: "2023",
          bg: "linear-gradient(135deg,#3a1a0d,#7e3a1a)",
        },
        {
          category: "Branding",
          title: "Project Five",
          subtitle: "Visual identity system",
          tag: "2022",
          bg: "linear-gradient(135deg,#2a1a3a,#5e1a7e)",
        },
      ],
    },
  },
};

FB.blocks.CUSTOM_BLOCK_DEFS = {
  textBlock: {
    label: "Custom Text",
    sublabel: "Heading + paragraph",
    icon: "T",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Your Headline Here",
      body: "Your body text goes here. Click to edit inline, or use the style panel on the right to change colours and spacing.",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#CDFE00",
      paddingV: 64,
      paddingH: 48,
    },
  },
  colorBlock: {
    label: "Colour Block",
    sublabel: "Full-width colour section",
    icon: "■",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Bold Statement.",
      body: "A full-colour section for emphasis.",
      bg: "#CDFE00",
      textColor: "#111111",
      paddingV: 80,
      paddingH: 48,
    },
  },
  imageTextTop: {
    label: "Image + Text (Top)",
    sublabel: "Image above text",
    icon: "◰",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that describes the image above. Click to edit any content.",
      imageUrl:
        "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
      imageAlt: "Section image",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 0,
      imagePosition: "top",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextBottom: {
    label: "Image + Text (Bottom)",
    sublabel: "Text above image",
    icon: "◳",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text that introduces the image below.",
      imageUrl:
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800",
      imageAlt: "Team collaboration",
      imageHeight: 400,
      imageFit: "cover",
      imageRadius: 12,
      imagePosition: "bottom",
      textAlign: "center",
      bg: "#f8fafc",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 48,
      paddingH: 48,
    },
  },
  imageTextLeft: {
    label: "Image + Text (Left)",
    sublabel: "Image left, text right",
    icon: "◧",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Great for feature descriptions or about sections.",
      imageUrl:
        "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600",
      imageAlt: "Feature showcase",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "left",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
  imageTextRight: {
    label: "Image + Text (Right)",
    sublabel: "Text left, image right",
    icon: "◨",
    iconBg: "#3a3a3a",
    iconColor: "#ccc",
    defaultProps: {
      headline: "Section Headline",
      body: "Supporting text beside the image. Perfect for testimonials or case studies.",
      imageUrl:
        "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600",
      imageAlt: "Case study",
      imageHeight: 360,
      imageFit: "cover",
      imageRadius: 8,
      imagePosition: "right",
      textAlign: "left",
      bg: "#ffffff",
      textColor: "#111111",
      accentColor: "#2563eb",
      paddingV: 64,
      paddingH: 48,
    },
  },
};

// All 18 ecommerce blocks migrated to widget files in widgets/ecom-*.js
// Empty object kept for backward compatibility with other modules
FB.blocks.ECOMMERCE_DEFS = {};
